services:
  - type: web
    runtime: node
    name: soundwave-studio
    plan: free
    buildCommand: npm --prefix server install
    startCommand: npm --prefix server start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
